
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: Formatting (black)
        entry: black
        language: python
        types_or: [python, pyi, jupyter]
        additional_dependencies: [".[jupyter]"]
      - id: ruff
        name: Linting + Import Sorting (ruff)
        entry: ruff check
        args: ["--fix"]
        types: [python]
        language: python
        additional_dependencies: ["ruff"]

exclude: ^(.svn|CVS|.bzr|.hg|.git|__pycache__|.tox|.ipynb_checkpoints|assets|tests/assets/|venv/|.venv/)
