name: CI

on: [pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install uv
        run: pip install uv
      
      - name: Install project dependencies
        run: uv sync
      
      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files
      
      - name: Run tests with coverage
        run: uv run pytest --cov=. --cov-report=term-missing --cov-report=xml
